In [1]:
import numpy as np
matriz_3x3 = np.arange(9).reshape(3, 3)
print(matriz_3x3)
matriz_identidad = np.identity(6)
print(matriz_identidad)

StatementMeta(SPKSmallCAPlab1, 22, 2, Finished, Available)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
