In [4]:
import numpy as np
ventas_mensuales = np.array([ [1200, 1500, 800, 2500], [1800, 1600, 900, 2800], [1500, 1400, 950, 2600], [1300, 1700, 850, 2700], [2000, 1800, 950, 2900], [1700, 1600, 900, 2700], [1400, 1300, 850, 2500], [1600, 1400, 1000, 2600], [1800, 1700, 950, 2900], [1900, 1500, 850, 2800], [1700, 1600, 900, 2600], [2100, 1800, 1000, 3000] ])
print(ventas_mensuales)
np.sum(ventas_mensuales, axis=0)

StatementMeta(SPK00, 6, 5, Finished, Available)

[[1200 1500  800 2500]
 [1800 1600  900 2800]
 [1500 1400  950 2600]
 [1300 1700  850 2700]
 [2000 1800  950 2900]
 [1700 1600  900 2700]
 [1400 1300  850 2500]
 [1600 1400 1000 2600]
 [1800 1700  950 2900]
 [1900 1500  850 2800]
 [1700 1600  900 2600]
 [2100 1800 1000 3000]]


array([20000, 18900, 10900, 32600])